name = "Base"
license = "MIT"
licenselink = "https://github.com/andrewvy/andrewvy.com/tree/master/themes/LICENSE.md"
description = "Base Theme for andrewvy.com"
homepage = "http://andrewvy.com"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Andrew Vy"
  homepage = "http://andrewvy.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
